<!DOCTYPE html>
<html>
  <head>
    <base href="/localhost" />
    <meta charset="UTF-8" />

    <title>Simple website CMS</title>

    <link rel="stylesheet" type="text/css" href="app/style.css" />
  </head>

  <body>
    <header>
      <h1>Main page for CMS editor</h1>
    </header>

    <nav>
      <a href="cms/pages">Get pages</a>
    </nav>

    <main>
      <?php if (isset($pages)) : ?>
        <ul>
          <?php foreach ($pages as $page) : ?>
            <li><?= $page['name'] ?></li>
          <?php endforeach ?>
        </ul>

      <?php endif ?>
    </main>
  </body>
</html>
