<!DOCTYPE html>
<html>
  <head>
    <base href="/localhost" />
    <meta charset="UTF-8" />

    <title>Simple website CMS</title>

    <link rel="stylesheet" type="text/css" href="app/admin/main.css" />
  </head>

  <body>
    <header>
      <h1>Main page for CMS editor</h1>
    </header>

    <nav>
      <a href="cms/pages">Get pages</a>
    </nav>

    <main>
      <?php if (isset($pages)) : ?>
        <?php
          $tempMn->include("group/pages-group/pages-group.phtml", '{
            "pages": ' . json_encode($pages) . '
          }');
        ?>

        <?php
          $tempMn->include("button/button.phtml", '{
            "action": "cms/pages/add",
            "title": "Add page"
          }');
        ?>

      <?php elseif (isset($page)) : ?>
        <?php require('app/admin/components/page/page.phtml') ?>
      <?php endif ?>
    </main>

    <script type="module" src="app/admin/main.js"></script>
  </body>
</html>
