<!DOCTYPE html>
<html>
  <head>
    <base href="/localhost" />
    <meta charset="UTF-8" />

    <title>Simple website CMS</title>

    <link rel="stylesheet" type="text/css" href="app/admin/main.css" />
  </head>

  <body>
    <header>
      <h1>Main page for CMS editor</h1>
    </header>

    <nav>
      <a href="cms/pages">Get pages</a>
    </nav>

    <main>
      <?php if (isset($pages)) : ?>
        <ul>
          <?php foreach ($pages as $page) : ?>
            <li><?= $page['name'] ?> - <a href="<?= "cms/pages/edit/" . $page['name'] ?>">Upravit</a></li>
          <?php endforeach ?>
        </ul>

      <?php elseif (isset($page)) : ?>
        <?php require('app/admin/components/page/page.phtml') ?>

      <?php endif ?>
    </main>

    <script type="module" src="app/admin/main.js"></script>
  </body>
</html>
