<section class="page" data-page-id="<?= $page['id'] ?>">
  <h2>Page detail</h2>

  <label>Page name:</label>
  <input type="text" id="name" value="<?= $page['name'] ?>" />

  <?php
    $checkbox = [
      'id' => "home",
      'label' => "Homepage:",
      'value' => $page['home'],
    ];
    require('app/admin/components/checkbox/checkbox.phtml');
  ?>

  <?php if (isset($blocks)) : ?>
    <ul>
      <?php foreach ($blocks as $block) : ?>
        <li class="block"><?= $block['name'] ?></li>
      <?php endforeach ?>
    </ul>
  <?php endif ?>

  <button id="saveBtn" type="button">
    Save
  </button>
</section>
