<section class="page" data-page-id="<?= $page['id'] ?>">
  <h2>Page detail</h2>

  <div class="page__data">
    <label>Page name:</label>
    <input type="text" id="name" value="<?= $page['name'] ?>" />

    <?php
      $checkbox = [
        'id' => "home",
        'label' => "Homepage:",
        'value' => $page['home'],
      ];
      require('app/admin/components/checkbox/checkbox.phtml');
    ?>
  </div>

  <?php
    $tempMn->include("button/add-block-button/add-block-button.phtml", '{
      "action": "",
      "title": "Add block"
    }');
  ?>

  <?php
    $tempMn->include("group/blocks-group/blocks-group.phtml", '{
      "blocks": ' . json_encode($blocks) . '
    }');
  ?>

  <button id="saveBtn" type="button">
    Save
  </button>
</section>
