<?php
  $id = isset($data->id) ? $data->id : null;
  $label = isset($data->label) ? $data->label : null;
  $value = isset($data->value) ? $data->value : null;

  $checked = $value === 1 ? 'checked="true"' : null;

  $attrs = trim(join(' ', [
    'class="checkbox"',
    $id ? 'for="' . $id . '"' : null,
  ]));
?>

<label <?= $attrs ?>><?= $label ?>
  <input type="checkbox" id="<?= $id ?>" <?= $checked ?> value="<?= $value ?>">
  <span class="checkbox-mark"></span>
</label>
