<?php
  $blocks = isset($data->blocks) ? $data->blocks : null;
?>

<div class="g-blocks">
  <ul>
    <?php foreach ($blocks as $block) : ?>
      <?php
        $blockName = "block_" . $block->id;
      ?>

      <li>
        <div class="block" data-id="<?= $block->id ?>" data-name="<?= $blockName ?>">
          <?= $block->block ?> with fields:

          <?php foreach ($block->fields as $field) {
            $tempMn->include("field/field.phtml", '{
              "type": "' . $field->type . '",
              "name": "' . $field->name . '",
              "content": ' . json_encode(isset($block->data) && isset($block->data->{$field->name}) ? $block->data->{$field->name} : null) .'
            }');
          } ?>

          <?php
            $tempMn->include("button/button.phtml", '{
              "action": "delete_target",
              "target": {
                "name": "' . $blockName . '",
                "type": "block",
                "parent": "g-blocks"
              },
              "title": "Delete block"
            }');
          ?>
        </div>
      </li>
    <?php endforeach ?>
  </ul>
</div>
