<?php
  $name = isset($data->name) ? $data->name : null;
  $type = isset($data->type) && in_array($data->type, ["text_line", "text_editor"]) ? $data->type : null;
  $content = isset($data->content) ? $data->content : null;
?>

<div class="field" data-field-name="<?= $name ?>">
  <?php if ($type === "text_line") : ?>
    <input type="text" value="<?= $content ?>" />

  <?php elseif ($type === "text_editor") : ?>
    <textarea class="editor field__editor" data-field-name="<?= $name ?>"><?= $content ?></textarea>
  <?php endif ?>
</div>
